# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Echo
      run:
        echo ${GITHUM_SHA::7}

    - name: Docker build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build -t ppyooy336/cicd-test:${GITHUB_SHA::7} .
        docker push ppyooy336/cicd-test:${GITHUB_SHA::7}
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SECRET_KEY }}
        #envs: GITHUB_SHA
        script: |
          docker pull ppyooy336/cicd-test:${GITHUB_SHA::7}
          docker tag ppyooy336/cicd-test:${GITHUB_SHA::7} cicd-test
          docker stop server
          docker run -d --rm --name server -p 8080:8080 cicd-test

